**1. Импорт библиотеки NumPy с общепринятым сокращением.**

In [42]:
import numpy as np

**2. Примеры создания массивов:**
 - из обычных списков;
 - с использованием функций `zeros`, `ones`, `arange` или аналогичных.

In [43]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr_zeros = np.zeros(5)
arr_ones = np.ones((2,3))
arr_seq = np.arange(0, 10, 2)
arr_eye = np.eye(5)
arr_mt = np.empty((3, 3))
np.set_printoptions(threshold=10000, precision=8)

**3. Демонстрация атрибутов:**
 - вывод формы (shape) и типа данных (dtype) для одного из массивов.

In [44]:
print(arr.shape)
arr.dtype

(2, 3)


dtype('int64')

**4. Примеры индексирования и срезов:**
 - получение отдельного элемента;
 - извлечение подмассива с помощью среза.

In [45]:
print(arr[0])
arr[1:4]

[1 2 3]


array([[4, 5, 6]])

**5. Примеры векторных операций и базовых статистик:**
 - поэлементное сложение или умножение массивов;
 - вычисление средней величины (`mean`) или другой простой статистики.

In [46]:
print(arr + arr)
print(arr * arr)
print(arr.mean())
print(arr.sum())
print(arr.min())

[[ 2  4  6]
 [ 8 10 12]]
[[ 1  4  9]
 [16 25 36]]
3.5
21
1
